export const INCREMENT_COUNT = "INCREMENT_COUNT";

export const REGISTER_IN_PROGRESS = "REGISTER_IN_PROGRESS";
export const REGISTER_COMPLETED = "REGISTER_COMPLETED";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const LOGIN_IN_PROGRESS = "LOGIN_IN_PROGRESS";
export const LOGIN_COMPLETED = "LOGIN_COMPLETED";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const USER_NOT_LOGGED_IN = "USER_NOT_LOGGED_IN";
export const USER_LOGGED_IN = "USER__LOGGED_IN";
